for i = 1, 10 do
	resource.AddFile("sound/stupid-ttt/allahu/akbar_" .. i .. ".wav")
end

resource.AddFile("models/weapons/v_sawedoff.mdl")
resource.AddFile("models/weapons/w_sawedoff.mdl")
resource.AddFile("materials/models/weapons/v_sawedoff/barrel.vtf")
resource.AddFile("materials/models/weapons/v_sawedoff/barrel_n.vtf")
resource.AddFile("materials/models/weapons/v_sawedoff/base.vtf")
resource.AddFile("materials/models/weapons/v_sawedoff/base_n.vtf")
resource.AddFile("materials/models/weapons/v_sawedoff/butt.vtf")
resource.AddFile("materials/models/weapons/v_sawedoff/butt_n.vtf")

resource.AddFile("models/weapons/v_p_drink.mdl")
resource.AddFile("models/weapons/w_p_drink.mdl")
resource.AddFile("materials/models/weapons/pdrink/m_drink_normal.vtf")
resource.AddFile("materials/models/weapons/pdrink/p_drink_sheet.vtf")
resource.AddFile("weapons/drink/open.wav")

resource.AddFile("sound/weapons/jihad/allahuackbar1.wav")
resource.AddFile("sound/weapons/jihad/allahuackbar2.wav")
resource.AddFile("sound/weapons/jihad/allahuackbar3.wav")
resource.AddFile("sound/weapons/jihad/allahuackbar4.wav")
resource.AddFile("sound/weapons/jihad/jihad_explosion.wav")
resource.AddFile("sound/weapons/jihad/jihad_beep.wav")

resource.AddFile("materials/vgui/ttt/icon_dbarrel.png")
resource.AddFile("materials/vgui/ttt/icon_ak47.png")
resource.AddFile("materials/vgui/ttt/icon_taser.png")
resource.AddFile("materials/vgui/ttt/icon_pepper.png")
resource.AddFile("materials/vgui/ttt/icon_gl.png")
resource.AddFile("materials/vgui/ttt/icon_mp5.png")
resource.AddFile("materials/vgui/ttt/icon_pdrank.png")
resource.AddFile("materials/vgui/ttt/icon_boomstick.png")
resource.AddFile("materials/vgui/ttt/icon_jihad.png")
resource.AddFile("materials/vgui/ttt/icon_ball.png")
resource.AddFile("materials/vgui/ttt/icon_deathstation.png")
resource.AddFile("materials/vgui/ttt/icon_dualies.png")
